### ISSUE TITLE
Ephemeral Runes

### ISSUE THREAD

**Issue by dyoder** [dashkite/runes#3]
See [design notes](https://github.com/dashkite/wiki/blob/main/docs/vedic-dolphin/ephemeral-runes.md#design-notes).

- [x] dashkite/enchant#11
- [x] dashkite/enchant#12
- [x] dashkite/enchant#13
- [x] dashkite/enchant#14
- [x] dashkite/runes#11
- [x] dashkite/runes#12
- [x] dashkite/enchant-rune#1
- [x] dashkite/runes-client#1
- [x] dashkite/runes-client#2
- [x] dashkite/runes-client#3
- [x] dashkite/guardian#5
- [x] dashkite/guardian#6

**Comment by dyoder** [comment]
See [design notes](https://github.com/dashkite/wiki/blob/main/docs/vedic-dolphin/ephemeral-runes.md#design-notes).

- [ ] `ok` condition action [Enchant]
- [ ] `authorization scheme` condition action [Enchant]
- [ ] Add `name` property to Runes [Guardian]
- [ ] Change `issue rune` to JSON 64 encode (rather than specifying that in the policy) [Enchant]
- [ ] `swap runes` action [Enchant]
- [ ] Use fresh context when evaluating Runes [Runes]
- [ ] Add `bind` function to Runes [Runes]
- [ ] Allow multiple Runes for a *(domain, name, method)* tuple [Runes Client]
- [ ] Select all matching Runes when making requests [Vega Client]
- [ ] Remove expired Runes when attempting matches [Vega Client]
- [ ] Try each matching Rune when authorizing, sorted in ascending order by the number of resolvers  [Rune Authorizer]
